### PR TITLE
Fix/desktop/53 gedrehtes bild kopieren

### LINKED ISSUE #53: Gedrehtes Bild kopieren
Wenn das angezeigt bild gedreht war soll auch das kopierte gedreht sein

### PR DESCRIPTION
**Pull request by GrumpyDucc**

### CODE REVIEW

File: desktop/src/main/kotlin/com/github/picture2pc/desktop/ui/main/elements/RotationButtons.kt [hunk 1]
```diff
@@ -35,6 +38,7 @@ fun RotationButtons(
         ) {
             mDVM.rotationState.value =
```
Comment (mightytry) [inline desktop/src/main/kotlin/com/github/picture2pc/desktop/ui/main/elements/RotationButtons.kt]: Not good to do here, if needed can be done in pDVM because it already has the mDVM

File: desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/PictureDisplayViewModel.kt [hunk 2]
```diff
@@ -61,9 +61,16 @@ class PictureDisplayViewModel(
         this.displayPictureSize = displayPictureSize
     }
 
+    fun rotate(clockwise: Boolean) {
+        pP.rotate(clockwise)
+    }
+
     fun reset() {
         mHVM.clear()
-        setPicture(pictures.replayCache[selectedPictureIndex.value])
```
Comment (mightytry) [inline desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/PictureDisplayViewModel.kt:70]: could have been done like `setPicture(pictures.replayCache[selectedPictureIndex.value]  ?: return)`. Just for future

File: desktop/src/main/kotlin/com/github/picture2pc/desktop/ui/main/MainScreen.kt [hunk 3]
```diff
@@ -66,45 +57,10 @@ fun MainScreen(
                     ) { Picture() }
```
Comment (mightytry) [inline desktop/src/main/kotlin/com/github/picture2pc/desktop/ui/main/MainScreen.kt]: For the picture, there are 4 Boxes inside of eachother when it only needs to be one. 3 in this file and one in Picture
