### PR TITLE
Fix/common/101 potential circular package issue when forwarding to both network adapters

### LINKED ISSUE #101: Potential circular package issue when forwarding to both network adapters
When implementing the new feature to forward packages to both network adapters, there is a theoretical possibility of creating a circular package loop. This could occur if forwarded packages are repeatedly sent between the adapters, leading to network congestion or unexpected behavior.

Steps to reproduce:
1. Enable forwarding of packages to both network adapters.
2. Observe the flow of network traffic.
3. Check if packages are being forwarded back and forth between adapters indefinitely.

Expected behavior:
Packages should be forwarded without causing an endless loop between network adapters.

Actual behavior:
There is a risk of circular forwarding, which may result in repetitive network traffic and undesirable side effects.

### PR DESCRIPTION
**Pull request by mightytry**

### CODE REVIEW

File: common/src/main/kotlin/com/github/picture2pc/common/net/networkpayloadtransceiver/impl/multicast/MulticastConstants.kt [hunk 1]
```diff
@@ -1,7 +1,7 @@
 package com.github.picture2pc.common.net.networkpayloadtransceiver.impl.multicast
 
 object MulticastConstants {
-    const val ADDRESS = "232.242.119.181"
+    const val ADDRESS = "224.0.0.69"
```
Comment (GrumpyDucc) [inline common/src/main/kotlin/com/github/picture2pc/common/net/networkpayloadtransceiver/impl/multicast/MulticastConstants.kt:4]: Why this address change? (Nice)

File: common/src/main/kotlin/com/github/picture2pc/common/net/networkpayloadtransceiver/impl/multicast/MulticastPayloadTransceiver.kt [hunk 2]
```diff
@@ -60,11 +59,11 @@ class MulticastPayloadTransceiver(
                     return@launch
                 }
                 val payload = multicastSocket.receivePayload() ?: continue
-                launch {
+                /*launch {
                     withTimeoutOrNull(2000) {
                         sendPayloadExcluding(payload, multicastSocket)
                     }
-                }
+                }*/
```
Comment (GrumpyDucc) [inline common/src/main/kotlin/com/github/picture2pc/common/net/networkpayloadtransceiver/impl/multicast/MulticastPayloadTransceiver.kt]: Can this also be deleted or is it useful having this for later?

File: common/src/main/kotlin/com/github/picture2pc/common/net/networkpayloadtransceiver/impl/multicast/MulticastConstants.kt (hunk 1 above)
Comment (mightytry) [reply common/src/main/kotlin/com/github/picture2pc/common/net/networkpayloadtransceiver/impl/multicast/MulticastConstants.kt:4]: becuase I read that 224.0.0.0/24 has to be usesd for better compability across devices. The old address did not work with a Vodafone router.

**Review by GrumpyDucc — APPROVED** [review]
